### ISSUE TITLE
Keep the filter when an item is sold

### ISSUE THREAD

**Issue by kpontussvensson** [Andols0/BagSearchPlus#1]
Hey!

I love the addon and been looking at doing something similar myself before I found this. The only improvement I'd like to see is keeping the filter when an item is sold. I use this for example to filter out low ilvl-gear for fast vendoring. But when I sell an item the filter gets removed. Is this something you would like to add to it?

**Comment by Andols0** [comment]
Hello!

Thanks for telling me, i had never noticed this!

It should be fixed now if you update :)
